project_id = "wghsyeluwojspkyppyvv"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.claire-chat]
verify_jwt = false

[functions.send-event-reminders]
verify_jwt = false
